#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=dialoGPT
#SBATCH --cpus-per-task=4
#SBATCH --time=12:00:00
#SBATCH --mem=32000M
#SBATCH --output=dialoGPT.out
#SBATCH --ntasks=1

module purge
module load 2019
module load Python/3.7.5-foss-2019b
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243
module load NCCL/2.5.6-CUDA-10.1.243
module load Anaconda3/2018.12

# Your job starts in the directory where you call sbatch
cd $HOME/rational-dialog-model
# Activate your environment
source activate cdm
# Run your code
echo "running train_dialogpt"
srun python -u train_dialogpt.py

echo "finish"