#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=dialoGPT
#SBATCH --cpus-per-task=4
#SBATCH --time=12:00:00
#SBATCH --mem=32000M
#SBATCH --output=dialoGPT_%A.out
#SBATCH --ntasks=1

module purge
module load 2019
module load Python/3.7.5-foss-2019b
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243
module load NCCL/2.5.6-CUDA-10.1.243
module load Anaconda3/2018.12

# Your job starts in the directory where you call sbatch
cd $HOME/rational-dialog-model
# Activate your environment
source activate cdm
# Run your code
echo "running finetune_dialogpt.py"
srun python -u finetune_dialogpt.py --model_checkpoint microsoft/DialoGPT-medium --max_epochs 8 --fine_tune_dataset mutual_friends --save_path finetuned/dialoGPT-mutual_friends-model
srun python -u finetune_dialogpt.py --model_checkpoint microsoft/DialoGPT-medium --max_epochs 8 --fine_tune_dataset daily_dialog --save_path finetuned/dialoGPT-daily_dialog-model
echo "finish"

#push to lisa: rsync -av . lcur0343@lisa.surfsara.nl:~/rational-dialog-model
#pull logs from lisa: rsync -av lcur0343@lisa.surfsara.nl:~/rational-dialog-model/runs .
